# Basic
title: Acolyter
subtitle: A blog-orientation theme for Jekyll
welcome_message: Welcome Message
description: Description Message
creator: <a href="http://acolyter.github.io/">Acolyter</a>

url: "http://acolyter.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
# markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://acolyter.github.io/projects.html'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}
    - {title: About, description: About, url: 'http://acolyter.github.io/about.html#/bored'}
   


# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: Acolyter
    twitter: 
    gplus: 
    mail: 

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
